---
title: "Google Trend Analysis"
author: "Dhiar Niken Larasati"
date: '2022-09-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r package}
library(gtrendsR)
library(tidyverse)
library(here)
library(ggrepel)
library(prophet)
library(tseries)
library(Metrics)
```


## query google trend


ISO code : https://www.iso.org/obp/ui/#iso:code:3166:ID 

```{r}
?gtrends

gtrend <- gtrends(keyword = c("bbm","minyak goreng"), geo = "ID", time = "2022-01-01 2022-09-08", hl = "id-ID")
bbmigor_iot <- gtrend$interest_over_time %>%
  select(date,hits,keyword)
```

```{r, fig.width=12, fig.height=5}
top_bbm <- bbmigor_iot %>%
  filter(keyword=="bbm")%>%
  slice_max(hits,n=2)
top_migor <- bbmigor_iot %>%
  filter(keyword=="minyak goreng") %>%
  slice_max(hits, n= 3)

bbmigor_iot %>%
  ggplot(aes(x=date,y=hits, color= keyword)) +
  geom_line(size = 1) +
  labs(x = "date", y = "GTI", title ="Hits pencarian keyword BBM dan minyak goreng di Indonesia tahun 2022") + 
    geom_label_repel( aes(label=ifelse(hits %in% top_bbm$hits | hits %in% top_migor$hits, paste(as.character(date),":",as.character(hits)),"")),
    fontface = "italic",
    size=3,
    color="#0b421a"
  )

```

```{r, fig.height=5, fig.width=12}
bbmigor_region <-gtrend$interest_by_region
bbmigor_region %>%
  ggplot(aes(x=reorder(location,hits),y=hits,fill=keyword))+
  geom_col(position = "dodge")+
  labs(title="Hits pencarian keyword menurut Provinsi", x="provinsi",y="GTI")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5,hjust = 1))

```

## gtrend untuk peramalan GDP
category code : https://github.com/pat310/google-trends-api/wiki/Google-Trends-Categories

## GDP
```{r}
GDP <- read.csv(here("GDP_1.csv")) %>%
  mutate(date = as.Date(period))  
GDP_K <- GDP %>%
  filter(Sector == "K") %>%
    mutate(norm_GDP = ((GDP/max(GDP))*100)) 
```

```{r, fig.width=12,fig.height=5}
GDP_K %>%
  ggplot(aes(x=date,y=norm_GDP)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5,hjust = 1))
```

```{r, fig.height=5, fig.width=12}
gtrend_K <- gtrends(keyword = "", geo ="ID",hl = "id-ID", time = "2011-01-01 2022-09-08", category = 7)
K_iot <- gtrend_K$interest_over_time %>%
  select(date,hits) %>%
  rename(cat_K = hits) %>%
  mutate(date = as.Date(date),
         lag_K = lag(cat_K,12),
        y_on_y = (cat_K-lag_K)/lag_K*100)

K_iot %>%
  ggplot(aes(x=date,y=cat_K)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5)) +
  labs(x= "date",y="GTI")
```


```{r, fig.height=5,fig.width=12}
plot_k <- ggplot() +
  geom_line(data = K_iot,aes(x=date, y=cat_K, color="GTI sector K")) +
  geom_line(data = GDP_K,aes(x=date, y=norm_GDP, color = "GDP sector K"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(family="Times", color = "black", size = 10)) +
  labs(x="date", y="normalized value") +
  scale_color_manual(values = c("GTI sector K"="blue","GDP sector K"="red")) 

  
```

```{r, fig.height=5,fig.width=12}
GDP_K_growth <- GDP_K %>%
  filter(substr(as.character(date),1,4)!= "2011")

plot_growth <- 
  ggplot() +
  geom_line(data = K_iot,aes(x=date, y=y_on_y, color="GTI sector K")) +
  geom_line(data = GDP_K_growth,aes(x=date, y=growth, color = "GDP sector K"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(family="Times", color = "black", size = 10)) +
  labs(x="date", y="normalized value") +
  scale_color_manual(values = c("GTI sector K"="blue","GDP sector K"="red")) 

  
```

## aggregate monthly GTI to quarterly
```{r}
K_iot_model <- K_iot %>%
  filter(substr(as.character(date),1,4)!="2011")

ts_K <- ts(K_iot_model$y_on_y,start=c(2012,1),frequency = 12)
ts_K_quarterly <- aggregate(ts_K,nfrequency = 4)/3
ts_K_quarterly <-as.data.frame(ts_K_quarterly) %>%
  rename(GTI = x)

ts_k_model <- ts_K_quarterly %>%
  slice(1:n()-1)


GDP_K_growth <- cbind(GDP_K_growth,ts_k_model)

```

```{r, fig.height=5,fig.width=12}
plot_growth_Q <- GDP_K_growth %>%
  ggplot() +
  geom_line(aes(x=date, y=GTI, color="GTI sector K")) +
  geom_line(aes(x=date, y=growth, color = "GDP sector K"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(family="Times", color = "black", size = 10)) +
  labs(x="date", y="growth") +
  scale_color_manual(values = c("GTI sector K"="blue","GDP sector K"="red")) 
```

```{r}
tseries::adf.test(GDP_K_growth$GTI)
tseries::pp.test(GDP_K_growth$GTI)

tseries::adf.test(GDP_K_growth$growth)
tseries::pp.test(GDP_K_growth$growth)
```
## forecast GDP 
```{r}
GDP_K_model <- GDP_K_growth %>%
  rename(ds = date,
         y = GDP) %>%
  filter(ds < "2021-09-01")


m_reg <- prophet()
m_reg <- add_regressor(m_reg,'GTI') 
m_reg <- fit.prophet(m_reg,GDP_K_model)

m_future <- prophet::make_future_dataframe(m_reg, periods=5, freq = "quarter")
m_future$GTI <- ts_K_quarterly$GTI
m_predict<- as_tibble(predict(m_reg,m_future))

dyplot.prophet(m_reg, m_predict)
```
```{r}
GDP_K_growth_model <- GDP_K_growth %>%
  rename(ds = date,
         y = growth) %>%
  filter(ds < "2021-09-01")


m_reg <- prophet()
m_reg <- add_regressor(m_reg,'GTI') 
m_reg <- fit.prophet(m_reg,GDP_K_growth_model)

m_future <- prophet::make_future_dataframe(m_reg, periods=5, freq = "quarter")
m_future$GTI <- ts_K_quarterly$GTI
m_predict<- as_tibble(predict(m_reg,m_future))

dyplot.prophet(m_reg, m_predict)
```


```{r}
K_forecast <- m_predict %>%
  dplyr::mutate(date = as.Date(ds)) %>%
  select(date, yhat) %>%
  full_join(GDP_K_growth)

K_forecast_rmse <- K_forecast %>%
  slice(1:n()-1)

rmse(K_forecast_rmse$growth,K_forecast_rmse$yhat)
```

```{r, fig.width=12,fig.height=5}
K_forecast %>%
  ggplot() +
  geom_line(aes(x=date, y=yhat, color="growth fitted")) +
  geom_line(aes(x=date, y=growth, color = "growth actual"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        legend.title = element_blank(),
        legend.text = element_text(family="Times", color = "black", size = 10)) +
  labs(x="date", y="growth") +
  scale_color_manual(values = c("growth fitted"="blue","growth actual"="red")) 
```










